---
# tasks file for aervits.hadoop
  - name: download hadoop release
    get_url:
      url: "{{ hadoop_url }}"
      dest: "/tmp/{{ hadoop_version }}.tar.gz"
      checksum: "sha1:{{ hadoop_sha1_sum }}"

  - name: create hadoop directory
    file:
      path: /opt/hadoop
      state: directory
      owner: hadoop
      group: hadoop
      mode: 0775

  - name: extract hadoop release
    unarchive:
      src: "/tmp/{{ hadoop_version }}.tar.gz"
      dest: /opt/hadoop
      remote_src: yes
      keep_newer: yes
      creates: "/opt/hadoop/{{ hadoop_version }}"

  - name: create hadoop namenode directory
    file:
      path: /dev/hadoop
      state: directory
      owner: hadoop
      group: hadoop
      mode: 0775

  - name: create datanode short-circuit path directory
    file:
      path: /var/lib/hadoop-hdfs
      state: directory
      owner: hadoop
      group: hadoop
      mode: 0755

  - name: create directory for yarn.nodemanager.recovery.dir
    file:
      path: /var/log/hadoop-yarn
      state: directory
      owner: hadoop
      group: hadoop
      mode: 0755

  - name: configure core-site.xml
    template:
      src: templates/hadoop/core-site.xml
      dest: "/opt/hadoop/{{ hadoop_version }}/etc/hadoop/core-site.xml"

  - name: configure hdfs-site.xml
    template:
      src: templates/hadoop/hdfs-site.xml
      dest: "/opt/hadoop/{{ hadoop_version }}/etc/hadoop/hdfs-site.xml"

  - name: configure mapred-site.xml
    template:
      src: templates/hadoop/mapred-site.xml
      dest: "/opt/hadoop/{{ hadoop_version }}/etc/hadoop/mapred-site.xml"

  - name: configure yarn-site.xml
    template:
      src: templates/hadoop/yarn-site.xml
      dest: "/opt/hadoop/{{ hadoop_version }}/etc/hadoop/yarn-site.xml"

  - name: configure capacity-scheduler.xml
    template:
      src: templates/hadoop/capacity-scheduler.xml
      dest: "/opt/hadoop/{{ hadoop_version }}/etc/hadoop/capacity-scheduler.xml"

  - name: change hadoop directory permissions
    file:
      path: "/opt/hadoop/{{ hadoop_version }}"
      state: directory
      owner: hadoop
      group: hadoop
      mode: 0775
      recurse: yes

  - name: export HADOOP_HOME
    lineinfile:
      path: /etc/environment
      line: export HADOOP_HOME="/opt/hadoop/{{ hadoop_version  }}"
      state: present
      create: yes

  - name: alias hdfs command
    lineinfile:
      path: /etc/bashrc
      line: alias hdfs=$HADOOP_HOME/bin/hdfs
      state: present
      create: yes

  - name: alias hadoop command
    lineinfile:
      path: /etc/bashrc
      line: alias hadoop=$HADOOP_HOME/bin/hadoop
      state: present
      create: yes

  - name: alias yarn command
    lineinfile:
      path: /etc/bashrc
      line: alias yarn=$HADOOP_HOME/bin/yarn
      state: present
      create: yes
