---
# defaults file for aervits.spark---
  spark_version: spark-2.4.0
  hadoop_version: hadoop2.7
  spark_url: http://www-us.apache.org/dist/spark/{{ spark_version }}/{{ spark_version }}-bin-{{ hadoop_version }}.tgz
  spark_sha_sum: 5F4184E0 FE7E5C8A E67F5E6B C5DEEE88 1051CC71
                               2E9FF8AE DDF35297 24C00E40 2C94BB75 561DD951
                               7A372F06 C1FCB78D C7AE65DC BD4C156B 3BA4D8E2
                               67EC2936
