---
# tasks file for aervits.devtools

  - name: get all required prerequisites
    package:
      name: "{{ item }}"
      state: latest
    with_items: wget, git, unzip, zip, gcc, python-devel

  - name: download maven release "{{ maven_version }}"
    get_url:
      url: "{{ maven_url }}"
      dest: "/tmp/{{ maven_version }}.bin.tar.gz"
      checksum: "md5:{{ maven_md5_sum }}"

  - name: create maven directory
    file:
      path: /opt/maven
      state: directory

  - name: extract maven release
    unarchive:
      src: "/tmp/{{ maven_version }}.bin.tar.gz"
      dest: /opt/maven
      remote_src: yes
      keep_newer: yes
      creates: "/opt/maven/{{ maven_version }}"

  - name: add maven bin dir to system-wide $PATH.
    copy:
      dest: /etc/profile.d/maven-path.sh
      content: 'PATH=$PATH:/opt/maven/{{ maven_version }}/bin'

  - name: alternatives link for maven
    alternatives:
      name: mvn
      link: /usr/bin/mvn
      path: /opt/maven/{{ maven_version }}/bin/mvn
