---
- hosts: all
  roles:
#    - aervits.jdk
#    - aervits.ssh
#    - aervits.users
    - aervits.hosts
#    - aervits.common
#    - aervits.hadoop
  remote_user: vagrant
  become: true
  vars:
    usernames:
       - hadoop
       - vagrant
