---
- hosts: all
  roles:
    - aervits.jdk
    - aervits.ssh
    - aervits.users
    - aervits.hosts
    - aervits.common
    - aervits.hadoop
    - aervits.hbase
    - aervits.phoenix
#    - aervits.spark # requires a compile with hadoop 3 for phoenix
  remote_user: vagrant
  become: true
  vars:
    usernames:
       - hbase
       - hadoop
       - vagrant
