---
- hosts: all
  roles:
#    - aervits.jdk
#    - aervits.ssh
#    - aervits.users
#    - aervits.hosts
#    - aervits.common
#    - aervits.hadoop
#    - aervits.hbase
    - aervits.phoenix
    - aervits.spark
  remote_user: vagrant
  become: true
  vars:
    usernames:
       - hbase
       - hadoop
       - vagrant
