---
- hosts: all
  roles:
    - aervits.jdk
    - aervits.ssh
    - aervits.users
    - aervits.hosts
    - aervits.common
    - aervits.hadoop
    - aervits.spark
  remote_user: vagrant
  become: true
  vars:
    usernames:
       - hadoop
       - vagrant
       - spark
