---
# tasks file for aervits.nifi
  - name: download nifi release
    get_url:
      url: "{{ nifi_url }}"
      dest: "/tmp/{{ nifi_version.string }}.bin.tar.gz"
      checksum: "sha512:{{ nifi_sha512_sum }}"

  - name: create nifi directory
    file:
      path: /opt/nifi
      state: directory
      owner: nifi
      group: nifi
      mode: 0775

  - name: extract nifi release
    unarchive:
      src: "/tmp/{{ nifi_version.string }}.bin.tar.gz"
      dest: /opt/nifi
      remote_src: yes
      keep_newer: yes
      creates: "/opt/nifi/{{ nifi_version.string }}"

  - name: export NIFI_HOME
    lineinfile:
      path: /etc/environment
      line: export NIFI_HOME="/opt/nifi/{{ nifi_version.string }}"
      state: present
      create: yes
