---
# tasks file for aervits.ambari-agent

  - name: download ambari repo
    get_url:
      url: "{{ ambari_repo }}"
      dest: /etc/yum.repos.d/ambari.repo
      force: yes

  - name: make sure ambari packages are current
    package:
      name: "{{ item }}"
      state: latest
    with_items: ambari-agent, ambari-metrics-hadoop-sink, ambari-logsearch-logfeeder, ambari-infra-solr, ambari-logsearch-portal, ambari-metrics-common, ambari-metrics-grafana, ambari-metrics-monitor, ambari-metrics-collector, ambari-infra-solr-client

  - name: stop ambari-agent
    service:
      name: ambari-agent
      state: stopped


  # need to add some logic to stop script from doing this every time
  # creates will only protect in case file doesn't exist

  - name: register ambari-agent hosts with ambari-server
    command: ambari-agent reset "{{ ambari_server_hostname }}"
    args:
#      creates: /etc/ambari-agent/conf/ambari-agent.ini

  - name: restart ambari-agent
    service:
      name: ambari-agent
      state: restarted
